admin:
  user: gimmeadmin
  password: gimmeadmin
port: 8080
secret: change_me_use_a_real_secret_32chars
s3:
  url: your.s3.url.cloud
  key: s3key
  secret: s3secret
  bucketName: gimme
  location: eu-west-1
  ssl: true
